ALTER TABLE AD_Column ADD AD_Column_UU VARCHAR(36);
ALTER TABLE AD_Element ADD AD_Element_UU VARCHAR(36);
ALTER TABLE AD_Field ADD AD_Field_UU VARCHAR(36);
ALTER TABLE AD_Sequence ADD AD_Sequence_UU VARCHAR(36);
ALTER TABLE AD_Tab ADD AD_Tab_UU VARCHAR(36);
ALTER TABLE AD_Table ADD AD_Table_UU VARCHAR(36);
