ALTER TABLE AD_Column DROP COLUMN AD_Column_UU;
ALTER TABLE AD_Element DROP COLUMN AD_Element_UU;
ALTER TABLE AD_Field DROP COLUMN AD_Field_UU;
ALTER TABLE AD_Sequence DROP COLUMN AD_Sequence_UU;
ALTER TABLE AD_Tab DROP COLUMN AD_Tab_UU;
ALTER TABLE AD_Table DROP COLUMN AD_Table_UU;
