ALTER TABLE AD_Column ADD COLUMN AD_Column_UU VARCHAR(36);
ALTER TABLE AD_Element ADD COLUMN AD_Element_UU VARCHAR(36);
ALTER TABLE AD_Field ADD COLUMN AD_Field_UU VARCHAR(36);
ALTER TABLE AD_Sequence ADD COLUMN AD_Sequence_UU VARCHAR(36);
ALTER TABLE AD_Tab ADD COLUMN AD_Tab_UU VARCHAR(36);
ALTER TABLE AD_Table ADD COLUMN AD_Table_UU VARCHAR(36);
